{{- if and .Values.syncer.enabled .Values.syncer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tapestry.syncer.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tapestry.syncer.labels" . | nindent 4 }}
  {{- with .Values.syncer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
