{{- if and .Values.syncer.enabled .Values.syncer.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tapestry.syncer.clusterRoleName" . }}
  labels:
    {{- include "tapestry.syncer.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["nodes", "pods", "serviceaccounts", "configmaps", "persistentvolumeclaims", "persistentvolumes", "secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["nodes/status", "pods/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["clusterbindings", "resourceleasingpolicies"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["clusterbindings/finalizers", "resourceleasingpolicies/finalizers"]
  verbs: ["update"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["clusterbindings/status", "resourceleasingpolicies/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
{{- end }}
