apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tapestry
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: tapestry
  name: tapestry-leader-election-rolebinding
  namespace: tapestry-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tapestry-leader-election-role
subjects:
- kind: ServiceAccount
  name: tapestry-manager
  namespace: tapestry-system