apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubeocean
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: kubeocean
  name: kubeocean-leader-election-rolebinding
  namespace: kubeocean-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeocean-leader-election-role
subjects:
- kind: ServiceAccount
  name: kubeocean-manager
  namespace: kubeocean-system