apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kubeocean
    app.kubernetes.io/instance: kubeocean-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: kubeocean
    control-plane: kubeocean-manager
  name: kubeocean-manager-metrics-service
  namespace: kubeocean-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: kubeocean-manager