{{- if .Values.features.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeocean-worker.clusterRoleName" . }}
  labels:
    {{- include "kubeocean-worker.labels" . | nindent 4 }}
    {{- with .Values.rbac.clusterRoleLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
# Cross-namespace permissions
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/status", "pods/log", "pods/exec", "pods/attach", "configmaps", "persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["nodes/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["persistentvolumes", "secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["resourceleasingpolicies"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["resourceleasingpolicies/finalizers"]
  verbs: ["update"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["resourceleasingpolicies/status"]
  verbs: ["get", "patch", "update"]
{{- end }}
