# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/cloud.tencent.com_clusterbindings.yaml
- bases/cloud.tencent.com_resourceleasingpolicies.yaml
#+kubebuilder:crdkustomizeresource

# the following config is for teaching kustomize how to do var substitution
#configurations:
#- kustomizeconfig.yaml