---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapestry-syncer
  namespace: tapestry-system
  labels:
    app.kubernetes.io/name: tapestry-syncer
    app.kubernetes.io/component: syncer
    app.kubernetes.io/part-of: tapestry
    app.kubernetes.io/managed-by: tapestry-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tapestry-syncer
  labels:
    app.kubernetes.io/name: tapestry-syncer
    app.kubernetes.io/component: syncer
    app.kubernetes.io/part-of: tapestry
    app.kubernetes.io/managed-by: tapestry-manager
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["nodes", "pods", "serviceaccounts", "configmaps", "persistentvolumeclaims", "persistentvolumes", "secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["nodes/status", "pods/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["clusterbindings", "resourceleasingpolicies"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["clusterbindings/finalizers", "resourceleasingpolicies/finalizers"]
  verbs: ["update"]
- apiGroups: ["cloud.tencent.com"]
  resources: ["clusterbindings/status", "resourceleasingpolicies/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["csinodes"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tapestry-syncer
  labels:
    app.kubernetes.io/name: tapestry-syncer
    app.kubernetes.io/component: syncer
    app.kubernetes.io/part-of: tapestry
    app.kubernetes.io/managed-by: tapestry-manager
subjects:
- kind: ServiceAccount
  name: tapestry-syncer
  namespace: tapestry-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tapestry-syncer