{{- if .Values.features.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tapestry-worker.roleName" . }}
  namespace: {{ include "tapestry-worker.namespaceName" . }}
  labels:
    {{- include "tapestry-worker.labels" . | nindent 4 }}
    {{- with .Values.rbac.roleLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
rules:
# Namespace-scoped permissions
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
{{- end }}
