{{- if .Values.features.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tapestry-worker.serviceAccountName" . }}
  namespace: {{ include "tapestry-worker.namespaceName" . }}
  labels:
    {{- include "tapestry-worker.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tapestry-worker.serviceAccountName" . }}
  namespace: {{ include "tapestry-worker.namespaceName" . }}
  annotations:
    kubernetes.io/service-account.name: {{ include "tapestry-worker.serviceAccountName" . }}
  labels:
    {{- include "tapestry-worker.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}