{{- if .Values.proxier.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubeocean.proxier.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "kubeocean.proxier.labels" . | nindent 4 }}
  {{- with .Values.proxier.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
