{{- if .Values.proxier.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeocean.proxier.clusterRoleBindingName" . }}
  labels:
    {{- include "kubeocean.proxier.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeocean.proxier.clusterRoleName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeocean.proxier.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
{{- end }}
