{{- if and .Values.syncer.enabled .Values.syncer.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubeocean.syncer.clusterRoleBindingName" . }}
  labels:
    {{- include "kubeocean.syncer.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubeocean.syncer.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubeocean.syncer.clusterRoleName" . }}
{{- end }}
